### ISSUE TITLE
353 GO terms

### ISSUE THREAD

**Issue by isgilman** [mossmatters/Angiosperms353#1]
Hello Matt, we've been working the 353 probes for a little while now but I haven't found a set of annotations to go along with the loci. We can annotate them ourselves using online databases, but I thought there may be a set of annotations that you and the group that designed the probes prefer. Is there a standard set of GO terms available?

Thanks,
Ian

**Comment by mossmatters** [comment]
Ian,

GO annotations for the Arabidopsis orthologs of the 353 genes can be found in the Dryad repository associated with the paper:https://datadryad.org/stash/dataset/doi:10.5061/dryad.s3h9r6j

I think the file got uploaded with a strange name but it should be .tar.gzip and contains annotations at two different levels (GO vs GoSlim). Let me know if you have any trouble or questions with the file!
